name       : mailnag
version    : 1.2.1
release    : 2
source     :
    - https://github.com/pulb/mailnag/archive/v1.2.1.tar.gz : ec7ac027d93bc7d88fc270858f5a181453a6ff07f43cab20563d185818801fee
license    : GPL-2.0
component  : network.mail
summary    : Mailnag is a daemon program that checks POP3 and IMAP servers for new mail
description: |
    Mailnag is a daemon program that checks POP3 and IMAP servers for new mail
rundeps  :
    - python-gobject2
    - pyxdg
build      : |
    %python_setup
install    : |
    %python_install
