name       : mailnag
version    : 2.0.0
release    : 5
source     :
    - https://github.com/pulb/mailnag/archive/v2.0.0.tar.gz : 9e57afac6e730846414ea304ba096387ce4d4f493fb3e4bf0feabf074e794974
license    : GPL-2.0
component  : network.mail
summary    : Mailnag is a daemon program that checks POP3 and IMAP servers for new mail
description: |
    Mailnag is a daemon program that checks POP3 and IMAP servers for new mail
rundeps    :
    - gst-plugins-base
    - libnotify
    - libsecret
    - python-gobject
    - python3-dbus
    - pyxdg
build      : |
    %python3_setup
install    : |
    %python3_install
